# Generated by Django 4.2.1 on 2023-06-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandwritingPerception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(upload_to='perceptions/')),
                ('output_text', models.CharField(max_length=255)),
                ('missing_characters_count', models.IntegerField()),
                ('missing_characters_percentage', models.FloatField()),
            ],
        ),
    ]
